Update to output error codes on fails.

diff --git a/.github/workflows/audit-reports.yml b/.github/workflows/audit-reports.yml
--- a/.github/workflows/audit-reports.yml
+++ b/.github/workflows/audit-reports.yml
@@ -53,18 +53,21 @@ jobs:
         run: |
           OUTPUT=$(azure-audit all --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/all-resources.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Run Audit CLI on Networking Resources"
         continue-on-error: true
         run: |
           OUTPUT=$(azure-audit networking --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/networking-resources.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Run Audit CLI on Storage Resources"
         continue-on-error: true
         run: |
           OUTPUT=$(azure-audit storage --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/storage-resources.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Commit and Push Command Outputs"
         continue-on-error: true
diff --git a/.github/workflows/cost-reports.yml b/.github/workflows/cost-reports.yml
--- a/.github/workflows/cost-reports.yml
+++ b/.github/workflows/cost-reports.yml
@@ -143,24 +143,28 @@ jobs:
         run: |
           OUTPUT=$(azure-cost dailyCosts --dimension ResourceGroup --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/daily-costs.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Run Cost by Resource Report"
         continue-on-error: true
         run: |
           OUTPUT=$(azure-cost costByResource --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/cost-by-resource.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
           
       - name: "Run Cost Anomalies by Resource Report"
         continue-on-error: true
         run: |
           OUTPUT=$(azure-cost detectAnomalies --dimension "ResourceId" --recent-activity-days 30 --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/anomalies-by-resource.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Run Accumulated Cost Report for All Resources"
         continue-on-error: true
         run: |
           OUTPUT=$(azure-cost accumulatedCost --output Markdown)
           if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/accumulated-cost.md; fi
+          if [ $? -ne 0 ]; then echo "Error code was: $?"; fi
 
       - name: "Run Summary Report Generation"
         continue-on-error: true
